@startuml

hide empty description


[*] -> AA
state AA #red
AA --> LK
AA --> AP
AA --> IZ
AA --> PC
AA -[#red,bold]-> QD
state QD #red
LK --> XM
AP --> ON
IZ --> QB
PC --> YF
QD -[#red,bold]-> UK
state UK #red
XM : 3
XM --> QV
XM --> YE
XM --> BS
XM --> BQ
ON --> EU
QB : 4
QB --> WH
QB --> KD
QB --> YH
YF --> CS
state CS #red
UK : 5
UK --> UV
UK --> DT
UK -[#red,bold]-> HU
state HU #red
QV --> II
YE --> WS
BS --> YH
BQ --> KF
state KF #red
EU : 13
EU --> IR
EU --> DT
EU --> XA
WH --> HA
KD --> KG
CS : 9
CS -[#red,bold]-> GT
state GT #red
CS --> WS
CS -[#red,bold]-> TR
state TR #red
CS --> KG
UV --> AE
HU -[#red,bold]-> CO
state CO #red
II --> DS
KF : 12
KF --> HA
KF -[#red,bold]-> AL
state AL #red
KF -[#red,bold]-> JW
state JW #red
IR --> AE
XA --> CG
GT -[#red,bold]-> MN
state MN #red
TR -[#red,bold]-> AL
state AL #red
AE : 10
AE --> PT
CO : 18
CO -[#red,bold]-> ED
state ED #red
CO --> PT
DS : 16
JW -[#red,bold]-> AD
state AD #red
CG --> QN
MN : 25
ED -[#red,bold]-> XN
state XN #red
AD -[#red,bold]-> SE
state SE #red
QN : 21
QN --> RI
XN -[#red,bold]-> IJ
state IJ #red
SE : 17
SE -[#red,bold]-> YR
state YR #red
RI --> GJ
IJ : 24
IJ -[#red,bold]-> WE
state WE #red
YR -[#red,bold]-> OS
state OS #red
GJ : 20
WE -[#red,bold]-> NA
OS -[#red,bold]-> NA
state NA #red
NA : 23

@enduml
