@startuml

[*] -> AA

AA --> LK
AA --> AP
AA --> IZ
AA --> PC
AA --> QD
LK --> XM
AP --> ON
IZ --> QB
PC --> YF
QD --> UK
XM : 3
XM --> QV
XM --> YE
XM --> BS
XM --> BQ
ON --> EU
QB : 4
QB --> WH
QB --> KD
QB --> YH
YF --> CS
UK : 5
UK --> UV
UK --> DT
UK --> HU
QV --> II
YE --> WS
BS --> YH
BQ --> KF
EU : 13
EU --> IR
EU --> DT
EU --> XA
WH --> HA
KD --> KG
CS : 9
CS --> GT
CS --> WS
CS --> TR
CS --> KG
UV --> AE
HU --> CO
II --> DS
KF : 12
KF --> HA
KF --> AL
KF --> JW
IR --> AE
XA --> CG
GT --> MN
TR --> AL
AE : 10
AE --> PT
CO : 18
CO --> ED
CO --> PT
DS : 16
JW --> AD
CG --> QN
MN : 25
ED --> XN
AD --> SE
QN : 21
QN --> RI
XN --> IJ
SE : 17
SE --> YR
RI --> GJ
IJ : 24
IJ --> WE
YR --> OS
GJ : 20
WE --> NA
OS --> NA
NA : 23

@enduml
